baseURL = 'https://toddcford.github.io'
languageCode = 'en-us'
title = 'Todd Ford'
theme = "paper"
googleAnalytics = "G-CFFHQDG3GE"

[params]

color = 'gray'

linkedin = 'toddcford1123'
name = ''
bio = 'Software Engineer'
monoDarkIcon = true

[menu]

  # [[menu.main]]
  #   identifier = "about"
  #   name = "About"
  #   url = "/about/"
  #   weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10